language: java
cache:
    directories:
     - "$HOME/.m2/repository"
     - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "simsuard"
    token:
        secure: $TOKEN
        

services:
     - docker

jdk:
     - openjdk11

script:
     - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=SimSuard_sample-application-students
     - ls -l
     - ls -l sample-application-db-changelog-job/
     - pwd
     - docker build -t simonsuard/sample-application-db-changelog-job sample-application-db-changelog-job/
     - docker build -t simonsuard/sample-application-http-api-server sample-application-http-api-server/

deploy:
    provider: script
    script: bash docker_push
    on:
        branch: dev
