language: java
cache:
    directories:
     - "$HOME/.m2/repository"
     - "$HOME/.sonar/cache"

services:
     - docker

before_install:
     - docker build -t simon/java_api
     - docker run --name java_app java_api 

jdk:
     - openjdk11
script:
     - maven clean verify
     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
     - docker push "$DOCKER_USERNAME"/tp_devops
